[build]
command = "npm install && npm run build"
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 2

[env]
NODE_ENV = "production"